Repository yashasvini121/predictive-calc, pull requests merged in 2024-10, with the labels that each got.

#50 enhancement : home page
  App.py
  machine-learning.gif
Labels: gssoc, hacktoberfest-accepted, gssoc-extd, level1

#60 Update readme.md
  readme.md
Labels: gssoc, hacktoberfest-accepted, gssoc-extd, level1

#82 enhance : issue templates
  .github/ISSUE_TEMPLATE/add-new-model.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hacktoberfest, gssoc-ext, level1

#89 In continuation with PR #61 (Made necessary changes) (#41 issue)
  models/translator_app/README.md
  models/translator_app/assets/styles.css
  models/translator_app/translation.py
  models/translator_app/utils.py
  pages/Translator.py
Labels: hacktoberfest, gssoc-ext, level3

#91 Pull request template added , Fixed # 59
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#62 updated PS and Desc in of each model in pages.json and updated page h…
  .gitignore
  page_handler.py
  pages/pages.json
Labels: hacktoberfest-accepted, gssoc-ext, level1

#116 Bug Fix: Handled the FileNotFoundError and JSONDecodeError in formhandler.py
  form_handler.py
Labels: hacktoberfest-accepted, gssoc-ext, level1

#164 Remove the Landmark detection web-app
  form_configs/landmark_detection.json
  models/landmark_detection/predict.py
  pages/Landmark_Detection.py
  pages/pages.json
Labels: hacktoberfest-accepted, gssoc-ext, level1

#147 Text Summarization Model
  App.py
  models/text_sumarization/predict.py
  pages/Text Summarizer.py
  requirements.txt
Labels: changes-requested

#113 add new model named credit card estimator used to detect whether the …
  App.py
  form_configs/credit_card_fraud.json
  models/credit_card_fraud/data/creditcardcsvpresent.csv
  models/credit_card_fraud/model.py
  models/credit_card_fraud/modelEvaluation.py
  models/credit_card_fraud/predict.py
  models/credit_card_fraud/saved models/creditCardFraud_svc_model.pkl
  pages/Credit_Card_Fraud_Estimator.py
  pages/pages.json
Labels: changes-requested
